package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/rackn/rocket-skates/client/bootenvs"
	"github.com/rackn/rocket-skates/client/dhcp_leases"
	"github.com/rackn/rocket-skates/client/dhcp_reservations"
	"github.com/rackn/rocket-skates/client/dhcp_subnets"
	"github.com/rackn/rocket-skates/client/files"
	"github.com/rackn/rocket-skates/client/isos"
	"github.com/rackn/rocket-skates/client/machines"
	"github.com/rackn/rocket-skates/client/templates"
)

// Default rocket skates HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "127.0.0.1:8092"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/api/v3"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new rocket skates HTTP client.
func NewHTTPClient(formats strfmt.Registry) *RocketSkates {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new rocket skates HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *RocketSkates {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new rocket skates client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *RocketSkates {
	cli := new(RocketSkates)
	cli.Transport = transport

	cli.Bootenvs = bootenvs.New(transport, formats)

	cli.DhcpLeases = dhcp_leases.New(transport, formats)

	cli.DhcpReservations = dhcp_reservations.New(transport, formats)

	cli.DhcpSubnets = dhcp_subnets.New(transport, formats)

	cli.Files = files.New(transport, formats)

	cli.Isos = isos.New(transport, formats)

	cli.Machines = machines.New(transport, formats)

	cli.Templates = templates.New(transport, formats)

	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// RocketSkates is a client for rocket skates
type RocketSkates struct {
	Bootenvs *bootenvs.Client

	DhcpLeases *dhcp_leases.Client

	DhcpReservations *dhcp_reservations.Client

	DhcpSubnets *dhcp_subnets.Client

	Files *files.Client

	Isos *isos.Client

	Machines *machines.Client

	Templates *templates.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *RocketSkates) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.Bootenvs.SetTransport(transport)

	c.DhcpLeases.SetTransport(transport)

	c.DhcpReservations.SetTransport(transport)

	c.DhcpSubnets.SetTransport(transport)

	c.Files.SetTransport(transport)

	c.Isos.SetTransport(transport)

	c.Machines.SetTransport(transport)

	c.Templates.SetTransport(transport)

}
