package bootenvs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/rackn/rocket-skates/models"
)

// HTTP code for type PatchBootenvOK
const PatchBootenvOKCode int = 200

/*PatchBootenvOK patch bootenv o k

swagger:response patchBootenvOK
*/
type PatchBootenvOK struct {

	/*
	  In: Body
	*/
	Payload *models.BootenvOutput `json:"body,omitempty"`
}

// NewPatchBootenvOK creates PatchBootenvOK with default headers values
func NewPatchBootenvOK() *PatchBootenvOK {
	return &PatchBootenvOK{}
}

// WithPayload adds the payload to the patch bootenv o k response
func (o *PatchBootenvOK) WithPayload(payload *models.BootenvOutput) *PatchBootenvOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch bootenv o k response
func (o *PatchBootenvOK) SetPayload(payload *models.BootenvOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchBootenvOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type PatchBootenvUnauthorized
const PatchBootenvUnauthorizedCode int = 401

/*PatchBootenvUnauthorized patch bootenv unauthorized

swagger:response patchBootenvUnauthorized
*/
type PatchBootenvUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchBootenvUnauthorized creates PatchBootenvUnauthorized with default headers values
func NewPatchBootenvUnauthorized() *PatchBootenvUnauthorized {
	return &PatchBootenvUnauthorized{}
}

// WithPayload adds the payload to the patch bootenv unauthorized response
func (o *PatchBootenvUnauthorized) WithPayload(payload *models.Error) *PatchBootenvUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch bootenv unauthorized response
func (o *PatchBootenvUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchBootenvUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type PatchBootenvNotFound
const PatchBootenvNotFoundCode int = 404

/*PatchBootenvNotFound patch bootenv not found

swagger:response patchBootenvNotFound
*/
type PatchBootenvNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchBootenvNotFound creates PatchBootenvNotFound with default headers values
func NewPatchBootenvNotFound() *PatchBootenvNotFound {
	return &PatchBootenvNotFound{}
}

// WithPayload adds the payload to the patch bootenv not found response
func (o *PatchBootenvNotFound) WithPayload(payload *models.Error) *PatchBootenvNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch bootenv not found response
func (o *PatchBootenvNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchBootenvNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type PatchBootenvConflict
const PatchBootenvConflictCode int = 409

/*PatchBootenvConflict patch bootenv conflict

swagger:response patchBootenvConflict
*/
type PatchBootenvConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchBootenvConflict creates PatchBootenvConflict with default headers values
func NewPatchBootenvConflict() *PatchBootenvConflict {
	return &PatchBootenvConflict{}
}

// WithPayload adds the payload to the patch bootenv conflict response
func (o *PatchBootenvConflict) WithPayload(payload *models.Error) *PatchBootenvConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch bootenv conflict response
func (o *PatchBootenvConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchBootenvConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type PatchBootenvExpectationFailed
const PatchBootenvExpectationFailedCode int = 417

/*PatchBootenvExpectationFailed patch bootenv expectation failed

swagger:response patchBootenvExpectationFailed
*/
type PatchBootenvExpectationFailed struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchBootenvExpectationFailed creates PatchBootenvExpectationFailed with default headers values
func NewPatchBootenvExpectationFailed() *PatchBootenvExpectationFailed {
	return &PatchBootenvExpectationFailed{}
}

// WithPayload adds the payload to the patch bootenv expectation failed response
func (o *PatchBootenvExpectationFailed) WithPayload(payload *models.Error) *PatchBootenvExpectationFailed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch bootenv expectation failed response
func (o *PatchBootenvExpectationFailed) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchBootenvExpectationFailed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(417)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type PatchBootenvInternalServerError
const PatchBootenvInternalServerErrorCode int = 500

/*PatchBootenvInternalServerError patch bootenv internal server error

swagger:response patchBootenvInternalServerError
*/
type PatchBootenvInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchBootenvInternalServerError creates PatchBootenvInternalServerError with default headers values
func NewPatchBootenvInternalServerError() *PatchBootenvInternalServerError {
	return &PatchBootenvInternalServerError{}
}

// WithPayload adds the payload to the patch bootenv internal server error response
func (o *PatchBootenvInternalServerError) WithPayload(payload *models.Error) *PatchBootenvInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch bootenv internal server error response
func (o *PatchBootenvInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchBootenvInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
