package bootenvs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/rackn/rocket-skates/models"
)

// HTTP code for type PostBootenvOK
const PostBootenvOKCode int = 200

/*PostBootenvOK post bootenv o k

swagger:response postBootenvOK
*/
type PostBootenvOK struct {

	/*
	  In: Body
	*/
	Payload *models.BootenvOutput `json:"body,omitempty"`
}

// NewPostBootenvOK creates PostBootenvOK with default headers values
func NewPostBootenvOK() *PostBootenvOK {
	return &PostBootenvOK{}
}

// WithPayload adds the payload to the post bootenv o k response
func (o *PostBootenvOK) WithPayload(payload *models.BootenvOutput) *PostBootenvOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post bootenv o k response
func (o *PostBootenvOK) SetPayload(payload *models.BootenvOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostBootenvOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type PostBootenvCreated
const PostBootenvCreatedCode int = 201

/*PostBootenvCreated post bootenv created

swagger:response postBootenvCreated
*/
type PostBootenvCreated struct {

	/*
	  In: Body
	*/
	Payload *models.BootenvOutput `json:"body,omitempty"`
}

// NewPostBootenvCreated creates PostBootenvCreated with default headers values
func NewPostBootenvCreated() *PostBootenvCreated {
	return &PostBootenvCreated{}
}

// WithPayload adds the payload to the post bootenv created response
func (o *PostBootenvCreated) WithPayload(payload *models.BootenvOutput) *PostBootenvCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post bootenv created response
func (o *PostBootenvCreated) SetPayload(payload *models.BootenvOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostBootenvCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type PostBootenvUnauthorized
const PostBootenvUnauthorizedCode int = 401

/*PostBootenvUnauthorized post bootenv unauthorized

swagger:response postBootenvUnauthorized
*/
type PostBootenvUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostBootenvUnauthorized creates PostBootenvUnauthorized with default headers values
func NewPostBootenvUnauthorized() *PostBootenvUnauthorized {
	return &PostBootenvUnauthorized{}
}

// WithPayload adds the payload to the post bootenv unauthorized response
func (o *PostBootenvUnauthorized) WithPayload(payload *models.Error) *PostBootenvUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post bootenv unauthorized response
func (o *PostBootenvUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostBootenvUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type PostBootenvConflict
const PostBootenvConflictCode int = 409

/*PostBootenvConflict post bootenv conflict

swagger:response postBootenvConflict
*/
type PostBootenvConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostBootenvConflict creates PostBootenvConflict with default headers values
func NewPostBootenvConflict() *PostBootenvConflict {
	return &PostBootenvConflict{}
}

// WithPayload adds the payload to the post bootenv conflict response
func (o *PostBootenvConflict) WithPayload(payload *models.Error) *PostBootenvConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post bootenv conflict response
func (o *PostBootenvConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostBootenvConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type PostBootenvInternalServerError
const PostBootenvInternalServerErrorCode int = 500

/*PostBootenvInternalServerError post bootenv internal server error

swagger:response postBootenvInternalServerError
*/
type PostBootenvInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostBootenvInternalServerError creates PostBootenvInternalServerError with default headers values
func NewPostBootenvInternalServerError() *PostBootenvInternalServerError {
	return &PostBootenvInternalServerError{}
}

// WithPayload adds the payload to the post bootenv internal server error response
func (o *PostBootenvInternalServerError) WithPayload(payload *models.Error) *PostBootenvInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post bootenv internal server error response
func (o *PostBootenvInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostBootenvInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
