package bootenvs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/rackn/rocket-skates/models"
)

/*PutBootenvOK put bootenv o k

swagger:response putBootenvOK
*/
type PutBootenvOK struct {

	/*
	  In: Body
	*/
	Payload *models.BootenvInput `json:"body,omitempty"`
}

// NewPutBootenvOK creates PutBootenvOK with default headers values
func NewPutBootenvOK() *PutBootenvOK {
	return &PutBootenvOK{}
}

// WithPayload adds the payload to the put bootenv o k response
func (o *PutBootenvOK) WithPayload(payload *models.BootenvInput) *PutBootenvOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put bootenv o k response
func (o *PutBootenvOK) SetPayload(payload *models.BootenvInput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutBootenvOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PutBootenvUnauthorized put bootenv unauthorized

swagger:response putBootenvUnauthorized
*/
type PutBootenvUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Result `json:"body,omitempty"`
}

// NewPutBootenvUnauthorized creates PutBootenvUnauthorized with default headers values
func NewPutBootenvUnauthorized() *PutBootenvUnauthorized {
	return &PutBootenvUnauthorized{}
}

// WithPayload adds the payload to the put bootenv unauthorized response
func (o *PutBootenvUnauthorized) WithPayload(payload *models.Result) *PutBootenvUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put bootenv unauthorized response
func (o *PutBootenvUnauthorized) SetPayload(payload *models.Result) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutBootenvUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PutBootenvNotFound put bootenv not found

swagger:response putBootenvNotFound
*/
type PutBootenvNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Result `json:"body,omitempty"`
}

// NewPutBootenvNotFound creates PutBootenvNotFound with default headers values
func NewPutBootenvNotFound() *PutBootenvNotFound {
	return &PutBootenvNotFound{}
}

// WithPayload adds the payload to the put bootenv not found response
func (o *PutBootenvNotFound) WithPayload(payload *models.Result) *PutBootenvNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put bootenv not found response
func (o *PutBootenvNotFound) SetPayload(payload *models.Result) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutBootenvNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PutBootenvInternalServerError put bootenv internal server error

swagger:response putBootenvInternalServerError
*/
type PutBootenvInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Result `json:"body,omitempty"`
}

// NewPutBootenvInternalServerError creates PutBootenvInternalServerError with default headers values
func NewPutBootenvInternalServerError() *PutBootenvInternalServerError {
	return &PutBootenvInternalServerError{}
}

// WithPayload adds the payload to the put bootenv internal server error response
func (o *PutBootenvInternalServerError) WithPayload(payload *models.Result) *PutBootenvInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put bootenv internal server error response
func (o *PutBootenvInternalServerError) SetPayload(payload *models.Result) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutBootenvInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
