package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/rackn/rocket-skates/models"
)

// HTTP code for type PostFileCreated
const PostFileCreatedCode int = 201

/*PostFileCreated post file created

swagger:response postFileCreated
*/
type PostFileCreated struct {

	/*
	  In: Body
	*/
	Payload PostFileCreatedBody `json:"body,omitempty"`
}

// NewPostFileCreated creates PostFileCreated with default headers values
func NewPostFileCreated() *PostFileCreated {
	return &PostFileCreated{}
}

// WithPayload adds the payload to the post file created response
func (o *PostFileCreated) WithPayload(payload PostFileCreatedBody) *PostFileCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post file created response
func (o *PostFileCreated) SetPayload(payload PostFileCreatedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFileCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// HTTP code for type PostFileBadRequest
const PostFileBadRequestCode int = 400

/*PostFileBadRequest post file bad request

swagger:response postFileBadRequest
*/
type PostFileBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostFileBadRequest creates PostFileBadRequest with default headers values
func NewPostFileBadRequest() *PostFileBadRequest {
	return &PostFileBadRequest{}
}

// WithPayload adds the payload to the post file bad request response
func (o *PostFileBadRequest) WithPayload(payload *models.Error) *PostFileBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post file bad request response
func (o *PostFileBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFileBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type PostFileUnauthorized
const PostFileUnauthorizedCode int = 401

/*PostFileUnauthorized post file unauthorized

swagger:response postFileUnauthorized
*/
type PostFileUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostFileUnauthorized creates PostFileUnauthorized with default headers values
func NewPostFileUnauthorized() *PostFileUnauthorized {
	return &PostFileUnauthorized{}
}

// WithPayload adds the payload to the post file unauthorized response
func (o *PostFileUnauthorized) WithPayload(payload *models.Error) *PostFileUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post file unauthorized response
func (o *PostFileUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFileUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type PostFileConflict
const PostFileConflictCode int = 409

/*PostFileConflict post file conflict

swagger:response postFileConflict
*/
type PostFileConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostFileConflict creates PostFileConflict with default headers values
func NewPostFileConflict() *PostFileConflict {
	return &PostFileConflict{}
}

// WithPayload adds the payload to the post file conflict response
func (o *PostFileConflict) WithPayload(payload *models.Error) *PostFileConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post file conflict response
func (o *PostFileConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFileConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type PostFileInternalServerError
const PostFileInternalServerErrorCode int = 500

/*PostFileInternalServerError post file internal server error

swagger:response postFileInternalServerError
*/
type PostFileInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostFileInternalServerError creates PostFileInternalServerError with default headers values
func NewPostFileInternalServerError() *PostFileInternalServerError {
	return &PostFileInternalServerError{}
}

// WithPayload adds the payload to the post file internal server error response
func (o *PostFileInternalServerError) WithPayload(payload *models.Error) *PostFileInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post file internal server error response
func (o *PostFileInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFileInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type PostFileInsufficientStorage
const PostFileInsufficientStorageCode int = 507

/*PostFileInsufficientStorage post file insufficient storage

swagger:response postFileInsufficientStorage
*/
type PostFileInsufficientStorage struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostFileInsufficientStorage creates PostFileInsufficientStorage with default headers values
func NewPostFileInsufficientStorage() *PostFileInsufficientStorage {
	return &PostFileInsufficientStorage{}
}

// WithPayload adds the payload to the post file insufficient storage response
func (o *PostFileInsufficientStorage) WithPayload(payload *models.Error) *PostFileInsufficientStorage {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post file insufficient storage response
func (o *PostFileInsufficientStorage) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFileInsufficientStorage) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(507)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
