package dhcp_leases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteDhcpLeaseParams creates a new DeleteDhcpLeaseParams object
// with the default values initialized.
func NewDeleteDhcpLeaseParams() *DeleteDhcpLeaseParams {
	var ()
	return &DeleteDhcpLeaseParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDhcpLeaseParamsWithTimeout creates a new DeleteDhcpLeaseParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteDhcpLeaseParamsWithTimeout(timeout time.Duration) *DeleteDhcpLeaseParams {
	var ()
	return &DeleteDhcpLeaseParams{

		timeout: timeout,
	}
}

// NewDeleteDhcpLeaseParamsWithContext creates a new DeleteDhcpLeaseParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteDhcpLeaseParamsWithContext(ctx context.Context) *DeleteDhcpLeaseParams {
	var ()
	return &DeleteDhcpLeaseParams{

		Context: ctx,
	}
}

// NewDeleteDhcpLeaseParamsWithHTTPClient creates a new DeleteDhcpLeaseParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteDhcpLeaseParamsWithHTTPClient(client *http.Client) *DeleteDhcpLeaseParams {
	var ()
	return &DeleteDhcpLeaseParams{
		HTTPClient: client,
	}
}

/*DeleteDhcpLeaseParams contains all the parameters to send to the API endpoint
for the delete dhcp lease operation typically these are written to a http.Request
*/
type DeleteDhcpLeaseParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete dhcp lease params
func (o *DeleteDhcpLeaseParams) WithTimeout(timeout time.Duration) *DeleteDhcpLeaseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete dhcp lease params
func (o *DeleteDhcpLeaseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete dhcp lease params
func (o *DeleteDhcpLeaseParams) WithContext(ctx context.Context) *DeleteDhcpLeaseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete dhcp lease params
func (o *DeleteDhcpLeaseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete dhcp lease params
func (o *DeleteDhcpLeaseParams) WithHTTPClient(client *http.Client) *DeleteDhcpLeaseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete dhcp lease params
func (o *DeleteDhcpLeaseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete dhcp lease params
func (o *DeleteDhcpLeaseParams) WithID(id string) *DeleteDhcpLeaseParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete dhcp lease params
func (o *DeleteDhcpLeaseParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDhcpLeaseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
