package dhcp_leases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLISTDhcpLeasesParams creates a new LISTDhcpLeasesParams object
// with the default values initialized.
func NewLISTDhcpLeasesParams() *LISTDhcpLeasesParams {

	return &LISTDhcpLeasesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLISTDhcpLeasesParamsWithTimeout creates a new LISTDhcpLeasesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLISTDhcpLeasesParamsWithTimeout(timeout time.Duration) *LISTDhcpLeasesParams {

	return &LISTDhcpLeasesParams{

		timeout: timeout,
	}
}

// NewLISTDhcpLeasesParamsWithContext creates a new LISTDhcpLeasesParams object
// with the default values initialized, and the ability to set a context for a request
func NewLISTDhcpLeasesParamsWithContext(ctx context.Context) *LISTDhcpLeasesParams {

	return &LISTDhcpLeasesParams{

		Context: ctx,
	}
}

/*LISTDhcpLeasesParams contains all the parameters to send to the API endpoint
for the l i s t dhcp leases operation typically these are written to a http.Request
*/
type LISTDhcpLeasesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the l i s t dhcp leases params
func (o *LISTDhcpLeasesParams) WithTimeout(timeout time.Duration) *LISTDhcpLeasesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the l i s t dhcp leases params
func (o *LISTDhcpLeasesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the l i s t dhcp leases params
func (o *LISTDhcpLeasesParams) WithContext(ctx context.Context) *LISTDhcpLeasesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the l i s t dhcp leases params
func (o *LISTDhcpLeasesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *LISTDhcpLeasesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
