package dhcp_leases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListDhcpLeasesParams creates a new ListDhcpLeasesParams object
// with the default values initialized.
func NewListDhcpLeasesParams() *ListDhcpLeasesParams {

	return &ListDhcpLeasesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListDhcpLeasesParamsWithTimeout creates a new ListDhcpLeasesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListDhcpLeasesParamsWithTimeout(timeout time.Duration) *ListDhcpLeasesParams {

	return &ListDhcpLeasesParams{

		timeout: timeout,
	}
}

// NewListDhcpLeasesParamsWithContext creates a new ListDhcpLeasesParams object
// with the default values initialized, and the ability to set a context for a request
func NewListDhcpLeasesParamsWithContext(ctx context.Context) *ListDhcpLeasesParams {

	return &ListDhcpLeasesParams{

		Context: ctx,
	}
}

// NewListDhcpLeasesParamsWithHTTPClient creates a new ListDhcpLeasesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListDhcpLeasesParamsWithHTTPClient(client *http.Client) *ListDhcpLeasesParams {

	return &ListDhcpLeasesParams{
		HTTPClient: client,
	}
}

/*ListDhcpLeasesParams contains all the parameters to send to the API endpoint
for the list dhcp leases operation typically these are written to a http.Request
*/
type ListDhcpLeasesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list dhcp leases params
func (o *ListDhcpLeasesParams) WithTimeout(timeout time.Duration) *ListDhcpLeasesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list dhcp leases params
func (o *ListDhcpLeasesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list dhcp leases params
func (o *ListDhcpLeasesParams) WithContext(ctx context.Context) *ListDhcpLeasesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list dhcp leases params
func (o *ListDhcpLeasesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list dhcp leases params
func (o *ListDhcpLeasesParams) WithHTTPClient(client *http.Client) *ListDhcpLeasesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list dhcp leases params
func (o *ListDhcpLeasesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListDhcpLeasesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
