package dhcp_leases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/rackn/rocket-skates/models"
)

// NewPUTDhcpLeaseParams creates a new PUTDhcpLeaseParams object
// with the default values initialized.
func NewPUTDhcpLeaseParams() *PUTDhcpLeaseParams {
	var ()
	return &PUTDhcpLeaseParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPUTDhcpLeaseParamsWithTimeout creates a new PUTDhcpLeaseParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPUTDhcpLeaseParamsWithTimeout(timeout time.Duration) *PUTDhcpLeaseParams {
	var ()
	return &PUTDhcpLeaseParams{

		timeout: timeout,
	}
}

// NewPUTDhcpLeaseParamsWithContext creates a new PUTDhcpLeaseParams object
// with the default values initialized, and the ability to set a context for a request
func NewPUTDhcpLeaseParamsWithContext(ctx context.Context) *PUTDhcpLeaseParams {
	var ()
	return &PUTDhcpLeaseParams{

		Context: ctx,
	}
}

/*PUTDhcpLeaseParams contains all the parameters to send to the API endpoint
for the p u t dhcp lease operation typically these are written to a http.Request
*/
type PUTDhcpLeaseParams struct {

	/*Body*/
	Body *models.DhcpLeaseInput
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the p u t dhcp lease params
func (o *PUTDhcpLeaseParams) WithTimeout(timeout time.Duration) *PUTDhcpLeaseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p u t dhcp lease params
func (o *PUTDhcpLeaseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p u t dhcp lease params
func (o *PUTDhcpLeaseParams) WithContext(ctx context.Context) *PUTDhcpLeaseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p u t dhcp lease params
func (o *PUTDhcpLeaseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the p u t dhcp lease params
func (o *PUTDhcpLeaseParams) WithBody(body *models.DhcpLeaseInput) *PUTDhcpLeaseParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the p u t dhcp lease params
func (o *PUTDhcpLeaseParams) SetBody(body *models.DhcpLeaseInput) {
	o.Body = body
}

// WithID adds the id to the p u t dhcp lease params
func (o *PUTDhcpLeaseParams) WithID(id string) *PUTDhcpLeaseParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the p u t dhcp lease params
func (o *PUTDhcpLeaseParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PUTDhcpLeaseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.DhcpLeaseInput)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
