package templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteTemplateParams creates a new DeleteTemplateParams object
// with the default values initialized.
func NewDeleteTemplateParams() *DeleteTemplateParams {
	var ()
	return &DeleteTemplateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteTemplateParamsWithTimeout creates a new DeleteTemplateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteTemplateParamsWithTimeout(timeout time.Duration) *DeleteTemplateParams {
	var ()
	return &DeleteTemplateParams{

		timeout: timeout,
	}
}

// NewDeleteTemplateParamsWithContext creates a new DeleteTemplateParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteTemplateParamsWithContext(ctx context.Context) *DeleteTemplateParams {
	var ()
	return &DeleteTemplateParams{

		Context: ctx,
	}
}

// NewDeleteTemplateParamsWithHTTPClient creates a new DeleteTemplateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteTemplateParamsWithHTTPClient(client *http.Client) *DeleteTemplateParams {
	var ()
	return &DeleteTemplateParams{
		HTTPClient: client,
	}
}

/*DeleteTemplateParams contains all the parameters to send to the API endpoint
for the delete template operation typically these are written to a http.Request
*/
type DeleteTemplateParams struct {

	/*UUID*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete template params
func (o *DeleteTemplateParams) WithTimeout(timeout time.Duration) *DeleteTemplateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete template params
func (o *DeleteTemplateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete template params
func (o *DeleteTemplateParams) WithContext(ctx context.Context) *DeleteTemplateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete template params
func (o *DeleteTemplateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete template params
func (o *DeleteTemplateParams) WithHTTPClient(client *http.Client) *DeleteTemplateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete template params
func (o *DeleteTemplateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUUID adds the uuid to the delete template params
func (o *DeleteTemplateParams) WithUUID(uuid string) *DeleteTemplateParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the delete template params
func (o *DeleteTemplateParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteTemplateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
