package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/rackn/rocket-skates/models"
)

// HTTP code for type DeleteMachineNoContent
const DeleteMachineNoContentCode int = 204

/*DeleteMachineNoContent delete machine no content

swagger:response deleteMachineNoContent
*/
type DeleteMachineNoContent struct {
}

// NewDeleteMachineNoContent creates DeleteMachineNoContent with default headers values
func NewDeleteMachineNoContent() *DeleteMachineNoContent {
	return &DeleteMachineNoContent{}
}

// WriteResponse to the client
func (o *DeleteMachineNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

// HTTP code for type DeleteMachineUnauthorized
const DeleteMachineUnauthorizedCode int = 401

/*DeleteMachineUnauthorized delete machine unauthorized

swagger:response deleteMachineUnauthorized
*/
type DeleteMachineUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteMachineUnauthorized creates DeleteMachineUnauthorized with default headers values
func NewDeleteMachineUnauthorized() *DeleteMachineUnauthorized {
	return &DeleteMachineUnauthorized{}
}

// WithPayload adds the payload to the delete machine unauthorized response
func (o *DeleteMachineUnauthorized) WithPayload(payload *models.Error) *DeleteMachineUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete machine unauthorized response
func (o *DeleteMachineUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteMachineUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type DeleteMachineNotFound
const DeleteMachineNotFoundCode int = 404

/*DeleteMachineNotFound delete machine not found

swagger:response deleteMachineNotFound
*/
type DeleteMachineNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteMachineNotFound creates DeleteMachineNotFound with default headers values
func NewDeleteMachineNotFound() *DeleteMachineNotFound {
	return &DeleteMachineNotFound{}
}

// WithPayload adds the payload to the delete machine not found response
func (o *DeleteMachineNotFound) WithPayload(payload *models.Error) *DeleteMachineNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete machine not found response
func (o *DeleteMachineNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteMachineNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type DeleteMachineConflict
const DeleteMachineConflictCode int = 409

/*DeleteMachineConflict delete machine conflict

swagger:response deleteMachineConflict
*/
type DeleteMachineConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteMachineConflict creates DeleteMachineConflict with default headers values
func NewDeleteMachineConflict() *DeleteMachineConflict {
	return &DeleteMachineConflict{}
}

// WithPayload adds the payload to the delete machine conflict response
func (o *DeleteMachineConflict) WithPayload(payload *models.Error) *DeleteMachineConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete machine conflict response
func (o *DeleteMachineConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteMachineConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type DeleteMachineInternalServerError
const DeleteMachineInternalServerErrorCode int = 500

/*DeleteMachineInternalServerError delete machine internal server error

swagger:response deleteMachineInternalServerError
*/
type DeleteMachineInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteMachineInternalServerError creates DeleteMachineInternalServerError with default headers values
func NewDeleteMachineInternalServerError() *DeleteMachineInternalServerError {
	return &DeleteMachineInternalServerError{}
}

// WithPayload adds the payload to the delete machine internal server error response
func (o *DeleteMachineInternalServerError) WithPayload(payload *models.Error) *DeleteMachineInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete machine internal server error response
func (o *DeleteMachineInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteMachineInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
