package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteMachineHandlerFunc turns a function with the right signature into a delete machine handler
type DeleteMachineHandlerFunc func(DeleteMachineParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteMachineHandlerFunc) Handle(params DeleteMachineParams) middleware.Responder {
	return fn(params)
}

// DeleteMachineHandler interface for that can handle valid delete machine params
type DeleteMachineHandler interface {
	Handle(DeleteMachineParams) middleware.Responder
}

// NewDeleteMachine creates a new http.Handler for the delete machine operation
func NewDeleteMachine(ctx *middleware.Context, handler DeleteMachineHandler) *DeleteMachine {
	return &DeleteMachine{Context: ctx, Handler: handler}
}

/*DeleteMachine swagger:route DELETE /machines/{uuid} Machines deleteMachine

Delete Machine

*/
type DeleteMachine struct {
	Context *middleware.Context
	Handler DeleteMachineHandler
}

func (o *DeleteMachine) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewDeleteMachineParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
