package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/rackn/rocket-skates/models"
)

/*PatchMachineAccepted patch machine accepted

swagger:response patchMachineAccepted
*/
type PatchMachineAccepted struct {

	/*
	  In: Body
	*/
	Payload PatchMachineAcceptedBody `json:"body,omitempty"`
}

// NewPatchMachineAccepted creates PatchMachineAccepted with default headers values
func NewPatchMachineAccepted() *PatchMachineAccepted {
	return &PatchMachineAccepted{}
}

// WithPayload adds the payload to the patch machine accepted response
func (o *PatchMachineAccepted) WithPayload(payload PatchMachineAcceptedBody) *PatchMachineAccepted {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch machine accepted response
func (o *PatchMachineAccepted) SetPayload(payload PatchMachineAcceptedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchMachineAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(202)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*PatchMachineUnauthorized patch machine unauthorized

swagger:response patchMachineUnauthorized
*/
type PatchMachineUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Result `json:"body,omitempty"`
}

// NewPatchMachineUnauthorized creates PatchMachineUnauthorized with default headers values
func NewPatchMachineUnauthorized() *PatchMachineUnauthorized {
	return &PatchMachineUnauthorized{}
}

// WithPayload adds the payload to the patch machine unauthorized response
func (o *PatchMachineUnauthorized) WithPayload(payload *models.Result) *PatchMachineUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch machine unauthorized response
func (o *PatchMachineUnauthorized) SetPayload(payload *models.Result) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchMachineUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PatchMachineNotFound patch machine not found

swagger:response patchMachineNotFound
*/
type PatchMachineNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Result `json:"body,omitempty"`
}

// NewPatchMachineNotFound creates PatchMachineNotFound with default headers values
func NewPatchMachineNotFound() *PatchMachineNotFound {
	return &PatchMachineNotFound{}
}

// WithPayload adds the payload to the patch machine not found response
func (o *PatchMachineNotFound) WithPayload(payload *models.Result) *PatchMachineNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch machine not found response
func (o *PatchMachineNotFound) SetPayload(payload *models.Result) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchMachineNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PatchMachineExpectationFailed patch machine expectation failed

swagger:response patchMachineExpectationFailed
*/
type PatchMachineExpectationFailed struct {

	/*
	  In: Body
	*/
	Payload *models.Result `json:"body,omitempty"`
}

// NewPatchMachineExpectationFailed creates PatchMachineExpectationFailed with default headers values
func NewPatchMachineExpectationFailed() *PatchMachineExpectationFailed {
	return &PatchMachineExpectationFailed{}
}

// WithPayload adds the payload to the patch machine expectation failed response
func (o *PatchMachineExpectationFailed) WithPayload(payload *models.Result) *PatchMachineExpectationFailed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch machine expectation failed response
func (o *PatchMachineExpectationFailed) SetPayload(payload *models.Result) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchMachineExpectationFailed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(417)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PatchMachineInternalServerError patch machine internal server error

swagger:response patchMachineInternalServerError
*/
type PatchMachineInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Result `json:"body,omitempty"`
}

// NewPatchMachineInternalServerError creates PatchMachineInternalServerError with default headers values
func NewPatchMachineInternalServerError() *PatchMachineInternalServerError {
	return &PatchMachineInternalServerError{}
}

// WithPayload adds the payload to the patch machine internal server error response
func (o *PatchMachineInternalServerError) WithPayload(payload *models.Result) *PatchMachineInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch machine internal server error response
func (o *PatchMachineInternalServerError) SetPayload(payload *models.Result) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchMachineInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
