package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"github.com/rackn/rocket-skates/models"
)

// PostMachineHandlerFunc turns a function with the right signature into a post machine handler
type PostMachineHandlerFunc func(PostMachineParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PostMachineHandlerFunc) Handle(params PostMachineParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PostMachineHandler interface for that can handle valid post machine params
type PostMachineHandler interface {
	Handle(PostMachineParams, *models.Principal) middleware.Responder
}

// NewPostMachine creates a new http.Handler for the post machine operation
func NewPostMachine(ctx *middleware.Context, handler PostMachineHandler) *PostMachine {
	return &PostMachine{Context: ctx, Handler: handler}
}

/*PostMachine swagger:route POST /machines Machines postMachine

Create Machine

*/
type PostMachine struct {
	Context *middleware.Context
	Handler PostMachineHandler
}

func (o *PostMachine) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewPostMachineParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
