package bootenvs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/rackn/rocket-skates/models"
)

// NewPatchBootenvParams creates a new PatchBootenvParams object
// with the default values initialized.
func NewPatchBootenvParams() *PatchBootenvParams {
	var ()
	return &PatchBootenvParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchBootenvParamsWithTimeout creates a new PatchBootenvParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchBootenvParamsWithTimeout(timeout time.Duration) *PatchBootenvParams {
	var ()
	return &PatchBootenvParams{

		timeout: timeout,
	}
}

// NewPatchBootenvParamsWithContext creates a new PatchBootenvParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchBootenvParamsWithContext(ctx context.Context) *PatchBootenvParams {
	var ()
	return &PatchBootenvParams{

		Context: ctx,
	}
}

// NewPatchBootenvParamsWithHTTPClient creates a new PatchBootenvParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchBootenvParamsWithHTTPClient(client *http.Client) *PatchBootenvParams {
	var ()
	return &PatchBootenvParams{
		HTTPClient: client,
	}
}

/*PatchBootenvParams contains all the parameters to send to the API endpoint
for the patch bootenv operation typically these are written to a http.Request
*/
type PatchBootenvParams struct {

	/*Body*/
	Body models.Patchinput
	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch bootenv params
func (o *PatchBootenvParams) WithTimeout(timeout time.Duration) *PatchBootenvParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch bootenv params
func (o *PatchBootenvParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch bootenv params
func (o *PatchBootenvParams) WithContext(ctx context.Context) *PatchBootenvParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch bootenv params
func (o *PatchBootenvParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch bootenv params
func (o *PatchBootenvParams) WithHTTPClient(client *http.Client) *PatchBootenvParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch bootenv params
func (o *PatchBootenvParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch bootenv params
func (o *PatchBootenvParams) WithBody(body models.Patchinput) *PatchBootenvParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch bootenv params
func (o *PatchBootenvParams) SetBody(body models.Patchinput) {
	o.Body = body
}

// WithName adds the name to the patch bootenv params
func (o *PatchBootenvParams) WithName(name string) *PatchBootenvParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the patch bootenv params
func (o *PatchBootenvParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *PatchBootenvParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
