package dhcp_subnets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDELETEDhcpSubnetParams creates a new DELETEDhcpSubnetParams object
// with the default values initialized.
func NewDELETEDhcpSubnetParams() *DELETEDhcpSubnetParams {
	var ()
	return &DELETEDhcpSubnetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDELETEDhcpSubnetParamsWithTimeout creates a new DELETEDhcpSubnetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDELETEDhcpSubnetParamsWithTimeout(timeout time.Duration) *DELETEDhcpSubnetParams {
	var ()
	return &DELETEDhcpSubnetParams{

		timeout: timeout,
	}
}

// NewDELETEDhcpSubnetParamsWithContext creates a new DELETEDhcpSubnetParams object
// with the default values initialized, and the ability to set a context for a request
func NewDELETEDhcpSubnetParamsWithContext(ctx context.Context) *DELETEDhcpSubnetParams {
	var ()
	return &DELETEDhcpSubnetParams{

		Context: ctx,
	}
}

/*DELETEDhcpSubnetParams contains all the parameters to send to the API endpoint
for the d e l e t e dhcp subnet operation typically these are written to a http.Request
*/
type DELETEDhcpSubnetParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the d e l e t e dhcp subnet params
func (o *DELETEDhcpSubnetParams) WithTimeout(timeout time.Duration) *DELETEDhcpSubnetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the d e l e t e dhcp subnet params
func (o *DELETEDhcpSubnetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the d e l e t e dhcp subnet params
func (o *DELETEDhcpSubnetParams) WithContext(ctx context.Context) *DELETEDhcpSubnetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the d e l e t e dhcp subnet params
func (o *DELETEDhcpSubnetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the d e l e t e dhcp subnet params
func (o *DELETEDhcpSubnetParams) WithID(id string) *DELETEDhcpSubnetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the d e l e t e dhcp subnet params
func (o *DELETEDhcpSubnetParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DELETEDhcpSubnetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
