package dhcp_leases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/rackn/rocket-skates/models"
)

/*GETDhcpLeaseOK g e t dhcp lease o k

swagger:response gETDhcpLeaseOK
*/
type GETDhcpLeaseOK struct {

	/*
	  In: Body
	*/
	Payload *models.DhcpLeaseInput `json:"body,omitempty"`
}

// NewGETDhcpLeaseOK creates GETDhcpLeaseOK with default headers values
func NewGETDhcpLeaseOK() *GETDhcpLeaseOK {
	return &GETDhcpLeaseOK{}
}

// WithPayload adds the payload to the g e t dhcp lease o k response
func (o *GETDhcpLeaseOK) WithPayload(payload *models.DhcpLeaseInput) *GETDhcpLeaseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the g e t dhcp lease o k response
func (o *GETDhcpLeaseOK) SetPayload(payload *models.DhcpLeaseInput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GETDhcpLeaseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
