package dhcp_leases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/rackn/rocket-skates/models"
)

/*LISTDhcpLeasesOK l i s t dhcp leases o k

swagger:response lISTDhcpLeasesOK
*/
type LISTDhcpLeasesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.DhcpLeaseInput `json:"body,omitempty"`
}

// NewLISTDhcpLeasesOK creates LISTDhcpLeasesOK with default headers values
func NewLISTDhcpLeasesOK() *LISTDhcpLeasesOK {
	return &LISTDhcpLeasesOK{}
}

// WithPayload adds the payload to the l i s t dhcp leases o k response
func (o *LISTDhcpLeasesOK) WithPayload(payload []*models.DhcpLeaseInput) *LISTDhcpLeasesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the l i s t dhcp leases o k response
func (o *LISTDhcpLeasesOK) SetPayload(payload []*models.DhcpLeaseInput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LISTDhcpLeasesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.DhcpLeaseInput, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
