package dhcp_reservations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"github.com/rackn/rocket-skates/models"
)

// GETDhcpReservationHandlerFunc turns a function with the right signature into a g e t dhcp reservation handler
type GETDhcpReservationHandlerFunc func(GETDhcpReservationParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GETDhcpReservationHandlerFunc) Handle(params GETDhcpReservationParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GETDhcpReservationHandler interface for that can handle valid g e t dhcp reservation params
type GETDhcpReservationHandler interface {
	Handle(GETDhcpReservationParams, *models.Principal) middleware.Responder
}

// NewGETDhcpReservation creates a new http.Handler for the g e t dhcp reservation operation
func NewGETDhcpReservation(ctx *middleware.Context, handler GETDhcpReservationHandler) *GETDhcpReservation {
	return &GETDhcpReservation{Context: ctx, Handler: handler}
}

/*GETDhcpReservation swagger:route GET /reservations/{id} Dhcp reservations gETDhcpReservation

Get DHCP Reservation

*/
type GETDhcpReservation struct {
	Context *middleware.Context
	Handler GETDhcpReservationHandler
}

func (o *GETDhcpReservation) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGETDhcpReservationParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
