package dhcp_reservations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/rackn/rocket-skates/models"
)

// HTTP code for type GETDhcpReservationOK
const GETDhcpReservationOKCode int = 200

/*GETDhcpReservationOK g e t dhcp reservation o k

swagger:response gETDhcpReservationOK
*/
type GETDhcpReservationOK struct {

	/*
	  In: Body
	*/
	Payload *models.DhcpReservationInput `json:"body,omitempty"`
}

// NewGETDhcpReservationOK creates GETDhcpReservationOK with default headers values
func NewGETDhcpReservationOK() *GETDhcpReservationOK {
	return &GETDhcpReservationOK{}
}

// WithPayload adds the payload to the g e t dhcp reservation o k response
func (o *GETDhcpReservationOK) WithPayload(payload *models.DhcpReservationInput) *GETDhcpReservationOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the g e t dhcp reservation o k response
func (o *GETDhcpReservationOK) SetPayload(payload *models.DhcpReservationInput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GETDhcpReservationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
