package dhcp_reservations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/rackn/rocket-skates/models"
)

// HTTP code for type PUTDhcpReservationOK
const PUTDhcpReservationOKCode int = 200

/*PUTDhcpReservationOK p u t dhcp reservation o k

swagger:response pUTDhcpReservationOK
*/
type PUTDhcpReservationOK struct {

	/*
	  In: Body
	*/
	Payload *models.DhcpReservationInput `json:"body,omitempty"`
}

// NewPUTDhcpReservationOK creates PUTDhcpReservationOK with default headers values
func NewPUTDhcpReservationOK() *PUTDhcpReservationOK {
	return &PUTDhcpReservationOK{}
}

// WithPayload adds the payload to the p u t dhcp reservation o k response
func (o *PUTDhcpReservationOK) WithPayload(payload *models.DhcpReservationInput) *PUTDhcpReservationOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the p u t dhcp reservation o k response
func (o *PUTDhcpReservationOK) SetPayload(payload *models.DhcpReservationInput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PUTDhcpReservationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
