package dhcp_reservations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGETDhcpReservationParams creates a new GETDhcpReservationParams object
// with the default values initialized.
func NewGETDhcpReservationParams() *GETDhcpReservationParams {
	var ()
	return &GETDhcpReservationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGETDhcpReservationParamsWithTimeout creates a new GETDhcpReservationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGETDhcpReservationParamsWithTimeout(timeout time.Duration) *GETDhcpReservationParams {
	var ()
	return &GETDhcpReservationParams{

		timeout: timeout,
	}
}

// NewGETDhcpReservationParamsWithContext creates a new GETDhcpReservationParams object
// with the default values initialized, and the ability to set a context for a request
func NewGETDhcpReservationParamsWithContext(ctx context.Context) *GETDhcpReservationParams {
	var ()
	return &GETDhcpReservationParams{

		Context: ctx,
	}
}

// NewGETDhcpReservationParamsWithHTTPClient creates a new GETDhcpReservationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGETDhcpReservationParamsWithHTTPClient(client *http.Client) *GETDhcpReservationParams {
	var ()
	return &GETDhcpReservationParams{
		HTTPClient: client,
	}
}

/*GETDhcpReservationParams contains all the parameters to send to the API endpoint
for the g e t dhcp reservation operation typically these are written to a http.Request
*/
type GETDhcpReservationParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the g e t dhcp reservation params
func (o *GETDhcpReservationParams) WithTimeout(timeout time.Duration) *GETDhcpReservationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the g e t dhcp reservation params
func (o *GETDhcpReservationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the g e t dhcp reservation params
func (o *GETDhcpReservationParams) WithContext(ctx context.Context) *GETDhcpReservationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the g e t dhcp reservation params
func (o *GETDhcpReservationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the g e t dhcp reservation params
func (o *GETDhcpReservationParams) WithHTTPClient(client *http.Client) *GETDhcpReservationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the g e t dhcp reservation params
func (o *GETDhcpReservationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the g e t dhcp reservation params
func (o *GETDhcpReservationParams) WithID(id string) *GETDhcpReservationParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the g e t dhcp reservation params
func (o *GETDhcpReservationParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GETDhcpReservationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
