package dhcp_reservations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/rackn/rocket-skates/models"
)

// POSTDhcpReservationReader is a Reader for the POSTDhcpReservation structure.
type POSTDhcpReservationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *POSTDhcpReservationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPOSTDhcpReservationCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPOSTDhcpReservationCreated creates a POSTDhcpReservationCreated with default headers values
func NewPOSTDhcpReservationCreated() *POSTDhcpReservationCreated {
	return &POSTDhcpReservationCreated{}
}

/*POSTDhcpReservationCreated handles this case with default header values.

POSTDhcpReservationCreated p o s t dhcp reservation created
*/
type POSTDhcpReservationCreated struct {
	Payload *models.DhcpReservationInput
}

func (o *POSTDhcpReservationCreated) Error() string {
	return fmt.Sprintf("[POST /reservations][%d] pOSTDhcpReservationCreated  %+v", 201, o.Payload)
}

func (o *POSTDhcpReservationCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DhcpReservationInput)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
