package dhcp_subnets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/rackn/rocket-skates/models"
)

// HTTP code for type LISTDhcpSubnetsOK
const LISTDhcpSubnetsOKCode int = 200

/*LISTDhcpSubnetsOK l i s t dhcp subnets o k

swagger:response lISTDhcpSubnetsOK
*/
type LISTDhcpSubnetsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.DhcpSubnetInput `json:"body,omitempty"`
}

// NewLISTDhcpSubnetsOK creates LISTDhcpSubnetsOK with default headers values
func NewLISTDhcpSubnetsOK() *LISTDhcpSubnetsOK {
	return &LISTDhcpSubnetsOK{}
}

// WithPayload adds the payload to the l i s t dhcp subnets o k response
func (o *LISTDhcpSubnetsOK) WithPayload(payload []*models.DhcpSubnetInput) *LISTDhcpSubnetsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the l i s t dhcp subnets o k response
func (o *LISTDhcpSubnetsOK) SetPayload(payload []*models.DhcpSubnetInput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LISTDhcpSubnetsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.DhcpSubnetInput, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
