package dhcp_subnets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/rackn/rocket-skates/models"
)

// HTTP code for type POSTDhcpSubnetCreated
const POSTDhcpSubnetCreatedCode int = 201

/*POSTDhcpSubnetCreated p o s t dhcp subnet created

swagger:response pOSTDhcpSubnetCreated
*/
type POSTDhcpSubnetCreated struct {

	/*
	  In: Body
	*/
	Payload *models.DhcpSubnetInput `json:"body,omitempty"`
}

// NewPOSTDhcpSubnetCreated creates POSTDhcpSubnetCreated with default headers values
func NewPOSTDhcpSubnetCreated() *POSTDhcpSubnetCreated {
	return &POSTDhcpSubnetCreated{}
}

// WithPayload adds the payload to the p o s t dhcp subnet created response
func (o *POSTDhcpSubnetCreated) WithPayload(payload *models.DhcpSubnetInput) *POSTDhcpSubnetCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the p o s t dhcp subnet created response
func (o *POSTDhcpSubnetCreated) SetPayload(payload *models.DhcpSubnetInput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *POSTDhcpSubnetCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
