package templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/rackn/rocket-skates/models"
)

/*DeleteTemplateNoContent delete template no content

swagger:response deleteTemplateNoContent
*/
type DeleteTemplateNoContent struct {
}

// NewDeleteTemplateNoContent creates DeleteTemplateNoContent with default headers values
func NewDeleteTemplateNoContent() *DeleteTemplateNoContent {
	return &DeleteTemplateNoContent{}
}

// WriteResponse to the client
func (o *DeleteTemplateNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

/*DeleteTemplateNotFound delete template not found

swagger:response deleteTemplateNotFound
*/
type DeleteTemplateNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Result `json:"body,omitempty"`
}

// NewDeleteTemplateNotFound creates DeleteTemplateNotFound with default headers values
func NewDeleteTemplateNotFound() *DeleteTemplateNotFound {
	return &DeleteTemplateNotFound{}
}

// WithPayload adds the payload to the delete template not found response
func (o *DeleteTemplateNotFound) WithPayload(payload *models.Result) *DeleteTemplateNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete template not found response
func (o *DeleteTemplateNotFound) SetPayload(payload *models.Result) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTemplateNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteTemplateConflict delete template conflict

swagger:response deleteTemplateConflict
*/
type DeleteTemplateConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Result `json:"body,omitempty"`
}

// NewDeleteTemplateConflict creates DeleteTemplateConflict with default headers values
func NewDeleteTemplateConflict() *DeleteTemplateConflict {
	return &DeleteTemplateConflict{}
}

// WithPayload adds the payload to the delete template conflict response
func (o *DeleteTemplateConflict) WithPayload(payload *models.Result) *DeleteTemplateConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete template conflict response
func (o *DeleteTemplateConflict) SetPayload(payload *models.Result) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTemplateConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteTemplateInternalServerError delete template internal server error

swagger:response deleteTemplateInternalServerError
*/
type DeleteTemplateInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Result `json:"body,omitempty"`
}

// NewDeleteTemplateInternalServerError creates DeleteTemplateInternalServerError with default headers values
func NewDeleteTemplateInternalServerError() *DeleteTemplateInternalServerError {
	return &DeleteTemplateInternalServerError{}
}

// WithPayload adds the payload to the delete template internal server error response
func (o *DeleteTemplateInternalServerError) WithPayload(payload *models.Result) *DeleteTemplateInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete template internal server error response
func (o *DeleteTemplateInternalServerError) SetPayload(payload *models.Result) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTemplateInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
