package templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/rackn/rocket-skates/models"
)

// HTTP code for type ListTemplatesOK
const ListTemplatesOKCode int = 200

/*ListTemplatesOK list templates o k

swagger:response listTemplatesOK
*/
type ListTemplatesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.TemplateOutput `json:"body,omitempty"`
}

// NewListTemplatesOK creates ListTemplatesOK with default headers values
func NewListTemplatesOK() *ListTemplatesOK {
	return &ListTemplatesOK{}
}

// WithPayload adds the payload to the list templates o k response
func (o *ListTemplatesOK) WithPayload(payload []*models.TemplateOutput) *ListTemplatesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list templates o k response
func (o *ListTemplatesOK) SetPayload(payload []*models.TemplateOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListTemplatesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.TemplateOutput, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// HTTP code for type ListTemplatesUnauthorized
const ListTemplatesUnauthorizedCode int = 401

/*ListTemplatesUnauthorized list templates unauthorized

swagger:response listTemplatesUnauthorized
*/
type ListTemplatesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListTemplatesUnauthorized creates ListTemplatesUnauthorized with default headers values
func NewListTemplatesUnauthorized() *ListTemplatesUnauthorized {
	return &ListTemplatesUnauthorized{}
}

// WithPayload adds the payload to the list templates unauthorized response
func (o *ListTemplatesUnauthorized) WithPayload(payload *models.Error) *ListTemplatesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list templates unauthorized response
func (o *ListTemplatesUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListTemplatesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type ListTemplatesNotFound
const ListTemplatesNotFoundCode int = 404

/*ListTemplatesNotFound list templates not found

swagger:response listTemplatesNotFound
*/
type ListTemplatesNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListTemplatesNotFound creates ListTemplatesNotFound with default headers values
func NewListTemplatesNotFound() *ListTemplatesNotFound {
	return &ListTemplatesNotFound{}
}

// WithPayload adds the payload to the list templates not found response
func (o *ListTemplatesNotFound) WithPayload(payload *models.Error) *ListTemplatesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list templates not found response
func (o *ListTemplatesNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListTemplatesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// HTTP code for type ListTemplatesInternalServerError
const ListTemplatesInternalServerErrorCode int = 500

/*ListTemplatesInternalServerError list templates internal server error

swagger:response listTemplatesInternalServerError
*/
type ListTemplatesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListTemplatesInternalServerError creates ListTemplatesInternalServerError with default headers values
func NewListTemplatesInternalServerError() *ListTemplatesInternalServerError {
	return &ListTemplatesInternalServerError{}
}

// WithPayload adds the payload to the list templates internal server error response
func (o *ListTemplatesInternalServerError) WithPayload(payload *models.Error) *ListTemplatesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list templates internal server error response
func (o *ListTemplatesInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListTemplatesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
