package templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"github.com/rackn/rocket-skates/models"
)

// ListTemplatesHandlerFunc turns a function with the right signature into a list templates handler
type ListTemplatesHandlerFunc func(ListTemplatesParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn ListTemplatesHandlerFunc) Handle(params ListTemplatesParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// ListTemplatesHandler interface for that can handle valid list templates params
type ListTemplatesHandler interface {
	Handle(ListTemplatesParams, *models.Principal) middleware.Responder
}

// NewListTemplates creates a new http.Handler for the list templates operation
func NewListTemplates(ctx *middleware.Context, handler ListTemplatesHandler) *ListTemplates {
	return &ListTemplates{Context: ctx, Handler: handler}
}

/*ListTemplates swagger:route GET /templates Templates listTemplates

List Templates

*/
type ListTemplates struct {
	Context *middleware.Context
	Handler ListTemplatesHandler
}

func (o *ListTemplates) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewListTemplatesParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
